# Generated by Django 6.0.5 on 2026-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('environment', models.CharField(choices=[('dev', 'Desarrollo'), ('test', 'Testing'), ('prod', 'Producción')], default='test')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
