# Generated by Django 6.0.5 on 2026-05-14 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(default='€', max_length=10)),
                ('payment_state', models.CharField(choices=[('pending', 'Pago pendiente'), ('completed', 'Pago completado'), ('failed', 'Pago fallido'), ('refuned', 'Pago devuelto')], default='pending')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasarela.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Sin descripcion', max_length=500)),
                ('type', models.CharField(choices=[('connection_error', 'Error de conexion'), ('nonpayment', 'Impago'), ('timeout', 'Timeout'), ('authentication_error', 'Error de autenticacion'), ('devolution', 'Devolucion')])),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasarela.transaction')),
            ],
        ),
    ]
