# Generated by Django 6.0.5 on 2026-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela', '0002_alter_provider_name_transaction_incidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='type',
            field=models.CharField(choices=[('nonpayment', 'Impago'), ('connection_error', 'Error de conexion'), ('devolution', 'Devolucion'), ('timeout', 'Timeout'), ('authentication_error', 'Error de autenticacion')]),
        ),
    ]
